### PR TITLE
Add packages potentially helpful to new arch users

### PR DESCRIPTION
**Pull request by jshuping**
Supersedes the merge-conflicted https://github.com/pigmonkey/spark/pull/2

### CODE REVIEW

**Comment by pigmonkey** [comment]
Is there anything critical missing in the [light](https://aur.archlinux.org/packages/light) package that light-git provides? Given the choice, I always prefer using non-git AUR packages so that I don't have to manually check for updates. That only works when the author tags releases with an agreeable frequency though.

I wish there was some generic cardDAV query tool to use with Mutt instead of goobook (I'm pretty sure Google supports cardDAV these days). Right now I manually sync my cardDAV server (not Google) locally to [ppl](http://ppladdressbook.org/). ppl is great locally but doesn't talk with anything else. Maybe [pyCardDAV](http://lostpackets.de/pycarddav/pages/usage.html) would work.

**Comment by pigmonkey** [comment]
[khard](https://github.com/scheibler/khard/) may be the answer.

**Comment by jshuping** [comment]
Good question about 'light', I prefer 'light-git' as it adds the save/restore functionality, and I use it here:

```
xautolock -time 10 -locker "if ! pidof physlock > /dev/null; then light -O ; light -S 10 ; physlock; light -I ; fi" -detectsleep -secure &
```

Reason being, I haven't yet figured out how to make physlock and dpms get along, my backlight stays active when physlock is active, so that line will save the brightness, set it to 10%, lock, then restore brightness after unlock.  Our mutual friend said he has the same problem.

I barely use goobook, my plan is to use it temporarily until our mutual friend sets up a [radicale](http://radicale.org/) server :)

Generally speaking would you prefer I not submit PRs with software that you aren't using? Or perhaps I should just provide better detailed comments?  My thought was that, for someone else who finds this repo, it might be helpful for them to see some more choices / options.  Cheers!

**Comment by pigmonkey** [comment]
So far all this stuff is fine. About half of it is stuff I do use, but just forgot to add to the repo.

**Pull request merged**
