### PR TITLE
update some pkg locations and deps

### PR DESCRIPTION
**Pull request by jshuping**
I did a full/fresh install last week on a new Intel NUC machine.  Couple of packages have changed locations, couple of dependent packages were missing from lists.

### CODE REVIEW

**Comment by pigmonkey** [comment]
With `python-humanize` and `python-tqdm` in the official repos, we can just drop them from all tasks and allow pacman to grab them as dependencies, right? Otherwise looks good.

`rfkill` is actually installed as a TLP dependency in the laptop role, but I guess you wouldn't run that on the NUC, so it makes sense to be explicit about it in the bluetooth role.

**Comment by pigmonkey** [comment]
And rfkill is [now part of util-linux](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/util-linux&id=28dd439f02b867757ca109f4b43660c62223d9d7), so we should actually drop that task too.

**Comment by brett** [comment]
Ran into these issues over the weekend, plus 2 more:
- acpi_call-dkms
- tpacpi-bat 

@pigmonkey : how do you want this cleaned up so that it can be incorporated?

**Comment by pigmonkey** [comment]
Those tasks should be replaced with whatever packages have taken the place of the previously used ones.

If you're working with @jshuping you can incorporate the previous commits with his initial commits. Or send a new request. I have no preference.

**Pull request merged**
